name: Demo Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: mkdir -p artifactApp
    - run: mkdir -p artifactTests
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: test app with dotnet
      run: dotnet test WebApp/TestSite.sln
    - name: Publish app with dotnet
      run: dotnet publish WebApp/TestSite.sln -c Release -o ${{github.workspace}}/artifactApp
    - name: Build automated tests with dotnet
      run: dotnet build TestAutomation/DemoTests.sln -o "${{github.workspace}}/artifactTests"
    - name: Upload app artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: app
        path: artifactApp
    - name: Upload test artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: tests
        path: artifactTests
